name: Test, Build, and Deploy | Module 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.48.193.47.181 }}
          username: ${{ secrets.senpro-modul2 }}
          password: ${{ secrets.Senpro-Modul2 }}
          port: ${{ secrets.22 }}

          script: |
            ssh-add ~/.ssh/<KEY_NAME_FROM_TA>

            echo "Check project folder"

            if [ -d "${HOME}/senpro-github-action/" ]; then
              echo "Repository has not been cloned. Cloning..."

              mkdir -p ~/senpro-github-action
              cd ~/senpro-github-action

              git clone <PROJECT_REPOSITORY_LINK>

              cd ~/senpro-github-action

              echo "Install Package and Build Project"
              npm install
              npm run build

            else
              echo "Repository already exists. Building..."

              cd ~/senpro-github-action

              git pull origin main

              echo "Install Packages and Build Project"
              npm install
              npm run build
            fi