name: Test, Build, and Deploy | Module 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build test
        run: |
          npm ci
          npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app to Remote Server over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            TARGET_DIR="${HOME}/senpro-github-action"

            # Check if directory does NOT exist (! -d)
            if [ ! -d "$TARGET_DIR" ]; then
              echo "Repository not found. Cloning..."
              git clone <PROJECT_REPOSITORY_LINK> "$TARGET_DIR"
              cd "$TARGET_DIR"
            else
              echo "Repository exists. Updating..."
              cd "$TARGET_DIR"
              git fetch origin main
              git reset --hard origin/main
            fi

            echo "Installing dependencies and building..."
            npm ci
            npm run build